version: "3.9"

services:
  api:
    build:
      context: .
      target: app
    image: basf-bookrec:app
    env_file:
      - .env
    ports:
      - "8000:8000"
    # If you seed from a local data file, mount it read-only:
    volumes:
      - ./data:/app/data:ro
